# 1. Escolha a imagem base com Python
FROM python:3.9-slim

# 2. Instalar as dependências do sistema operacional necessárias para compilar pacotes C, como o reportlab
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libffi-dev \
    libssl-dev \
    python3-dev \
    libjpeg-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# 3. Definir o diretório de trabalho dentro do container
WORKDIR /app

# 4. Copiar o conteúdo do seu projeto para o diretório de trabalho no container
COPY . /app

# 5. Instalar as dependências Python do seu projeto a partir do requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# 6. Expor a porta que o seu app Flask vai rodar
EXPOSE 8000

# 7. Comando para iniciar o servidor com Gunicorn (app.py)
CMD ["gunicorn", "app:app", "--bind", "192.168.80.54:8000"]
