"""Adicionando setor e prioridade à tabela ticket

Revision ID: 5f7010aacbbd
Revises: 
Create Date: 2025-07-04 13:22:53.701016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7010aacbbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('ticket') as batch_op:
        batch_op.add_column(sa.Column('setor', sa.String(100), nullable=True))
        batch_op.add_column(sa.Column('prioridade', sa.String(50), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('prioridade')
        batch_op.drop_column('setor')

    # ### end Alembic commands ###
